### ISSUE TITLE
Mainnet bug - refresh button counter

### ISSUE THREAD

**Issue by dimyself** [vetherasset/vether-dapp#21]
Hi there! I don't suppose the bug bounty is still in effect? :) Or if this bug even qualifies... 

Anyway here is what I found in case you aren't already aware of it... I was just playing around on the site, and hit the refresh button to the left of the counter under "CURRENT ERA". It messed up the countdown timer, and I recorded it which is attached.

 I'm using Brave browser on Linux. Let me know if you need any other info. Thank you!

![vether_mainnet_bug](https://user-images.githubusercontent.com/36783626/82587560-08334e80-9b5f-11ea-8de5-1fbffa23fa0b.gif)

**Comment by strictly-scarce** [comment]
Thanks will address this now
