### ISSUE TITLE
Stats are not being displayed

### ISSUE THREAD

**Issue by idontuseversioncontrol** [vetherasset/vether-dapp#37]
https://vetherasset.org/stats
Stats are not loading for me since yesterday, it just spins infinitely.

<img width="1066" alt="Screen Shot 2020-05-27 at 16 36 24" src="https://user-images.githubusercontent.com/6132647/83034163-3c63af00-a038-11ea-96cb-0a71ff8035f3.png">

**Comment by yellowgh0st** [comment]
It works, that could have been API server side issue.
