### ISSUE TITLE
ADD: Dev Env

### ISSUE THREAD

**Issue by strictly-scarce** [vetherasset/vether-dapp#74]
Add the following:

- [x] firebase dev env
- [x] dev branch
- [x] dev deploy Github Action w/ firebase dev project
- [x] test
- [x] docs (readme)

**Comment by strictly-scarce** [comment]
Branch: https://github.com/vetherasset/vether-dapp/tree/dev
URL: https://vether-dapp-dev.web.app/overview

**Comment by yellowgh0st** [comment]
We need to preserver master as default branch because Vercel uses default production for production environment
and I can't change it at the moment.
